### ISSUE TITLE
Missing required `aws_ami` `owners` field

### ISSUE THREAD

**Issue by mcg** [cloudposse/terraform-aws-ec2-instance-group#6]
`data.aws_ami.info` is defined as:

```
data "aws_ami" "info" {
  filter {
    name   = "image-id"
    values = ["${var.ami}"]
  }
}
```

Which seems to be missing the required `owners` field.
Same issue as cloudposse/terraform-aws-ec2-instance#36

**Comment by aknysh** [comment]
thanks @mcg 
if you open a PR, we'll review it promptly

**Comment by aknysh** [comment]
fixed in https://github.com/cloudposse/terraform-aws-ec2-instance-group/releases/tag/0.3.0
